import json
import datetime
import os
from statistics import mean

# Configuration
INPUT_FILE = "sample_data.json"
OUTPUT_DIR = "output"
TEMPLATE_FILE = "templates/report_template.md"

def load_data(filepath):
    with open(filepath, 'r') as f:
        return json.load(f)

def analyze_data(data):
    total_interactions = len(data)
    stable_interactions = sum(1 for d in data if d['status'] == 'STABLE')
    collapsed_interactions = sum(1 for d in data if d['status'] == 'COLLAPSE_DETECTED')
    
    avg_ricci = mean([d['ricci_score'] for d in data])
    avg_fisher = mean([d['fisher_gap'] for d in data])
    
    integrity_score = (stable_interactions / total_interactions) * 100
    
    critical_findings = [d for d in data if d['status'] == 'COLLAPSE_DETECTED']
    
    return {
        "total": total_interactions,
        "stable": stable_interactions,
        "collapsed": collapsed_interactions,
        "avg_ricci": round(avg_ricci, 4),
        "avg_fisher": round(avg_fisher, 4),
        "integrity_score": round(integrity_score, 2),
        "critical_findings": critical_findings
    }

def generate_markdown(analysis, client_name="Demo Corp"):
    date_str = datetime.datetime.now().strftime("%Y-%m-%d")
    
    report = f"""# AHI Governance - AI Risk Technical Audit
**Client:** {client_name}
**Date:** {date_str}
**Status:** {'PASSED' if analysis['integrity_score'] > 90 else 'CRITICAL RISK'}

---

## 1. Executive Summary
This audit evaluates the structural integrity of the AI system used by **{client_name}**. The assessment utilizes AHI's proprietary **Ricci Curvature Flow** methodology to detect semantic hallucinations and topological collapse.

### Key Metrics
| Metric | Value | Status |
| :--- | :--- | :--- |
| **System Integrity Score** | **{analysis['integrity_score']}%** | {'✅ STABLE' if analysis['integrity_score'] > 90 else '⚠️ AT RISK'} |
| **Avg. Ricci Curvature** | {analysis['avg_ricci']} | (Target: > 0.85) |
| **Fisher Gap (Robustness)** | {analysis['avg_fisher']} | (Target: > 0.02) |
| **Total Interactions Analyzed** | {analysis['total']} | - |

---

## 2. Risk Analysis Map

### Stability Distribution
- **Stable Interactions:** {analysis['stable']}
- **Collapsed Interactions:** {analysis['collapsed']}

> **Architect's Note:** A Fisher Gap below 0.017372 indicates a high probability of adversarial susceptibility or model collapse.

---

## 3. Critical Findings (Hallucinations & Failures)

The following interactions triggered the **Geometric Lock** due to topological instability:

"""

    if analysis['critical_findings']:
        for finding in analysis['critical_findings']:
            report += f"""
### 🔴 Incident ID: `{finding['id']}`
- **Timestamp:** {finding['timestamp']}
- **Trigger Prompt:** "{finding['prompt']}"
- **System Response:** "{finding['response']}"
- **Metrics:** Ricci: `{finding['ricci_score']}` | Fisher Gap: `{finding['fisher_gap']}`
- **Diagnosis:** **TOPOLOGICAL COLLAPSE**. The model diverged from the truth manifold.
"""
    else:
        report += "\n*No critical failures detected during this audit window.*\n"

    report += """
---

## 4. Recommendations

1.  **Immediate Action:** Implement a **Geometric Lock** (Circuit Breaker) for prompts scoring < 0.20 Ricci Curvature.
2.  **Mitigation:** Retrain the RLHF layer using the *Sintergic Gauge* to penalize low-Fisher-gap outputs.
3.  **Monitoring:** Deploy "The Eye" dashboard for real-time observation of the `fisher_gap` metric.

---

**Generated by AHI Audit CLI**
*Sovereign Symbiosis Architecture*
"""
    return report

def main():
    print("AHI Audit Generator v1.0")
    print("------------------------")
    
    # 1. Load Data
    print(f"Loading data from {INPUT_FILE}...")
    try:
        data = load_data(INPUT_FILE)
    except FileNotFoundError:
        print(f"Error: {INPUT_FILE} not found.")
        return

    # 2. Analyze
    print("Analyzing geometric integrity...")
    analysis = analyze_data(data)
    
    # 3. Generate Report
    print("Generating report...")
    report_content = generate_markdown(analysis)
    
    # 4. Save
    output_filename = f"{OUTPUT_DIR}/AHI_Audit_Report_{datetime.datetime.now().strftime('%Y%m%d')}.md"
    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)
        
    with open(output_filename, 'w', encoding='utf-8') as f:
        f.write(report_content)
        
    print(f"✅ Report generated successfully: {output_filename}")
    print(f"Integrity Score: {analysis['integrity_score']}%")

if __name__ == "__main__":
    main()
